mysql:
  image: mysql:8.0
  container_name: mds-mysql
  volumes:
    - ./data/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=mds
    - MYSQL_USER=john
    - MYSQL_PASSWORD=password
  ports:
    - "8001:3306"
